// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA4sEhVT33HzzNabxTZGamvaMjiRJSjLk',
    appId: '1:623207308329:web:354a9ec65c019693595038',
    messagingSenderId: '623207308329',
    projectId: 'unify-cd6e4',
    authDomain: 'unify-cd6e4.firebaseapp.com',
    storageBucket: 'unify-cd6e4.appspot.com',
    measurementId: 'G-6BLQ2XRE53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2KEbkIAS-SLALelDEQr_BPoRo06h0wHk',
    appId: '1:623207308329:android:6d4b6e7168570451595038',
    messagingSenderId: '623207308329',
    projectId: 'unify-cd6e4',
    storageBucket: 'unify-cd6e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn0vVSuOxDn2--rBVHQyAlttNqg_MHr5w',
    appId: '1:623207308329:ios:a32b143db01165e0595038',
    messagingSenderId: '623207308329',
    projectId: 'unify-cd6e4',
    storageBucket: 'unify-cd6e4.appspot.com',
    iosBundleId: 'com.example.unify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn0vVSuOxDn2--rBVHQyAlttNqg_MHr5w',
    appId: '1:623207308329:ios:a20a110a56f3ccd8595038',
    messagingSenderId: '623207308329',
    projectId: 'unify-cd6e4',
    storageBucket: 'unify-cd6e4.appspot.com',
    iosBundleId: 'com.example.unify.RunnerTests',
  );
}
